SELECT
    monthname(ss.STATUS_DATE) AS month,
    COUNT(s.SHIPMENT_ID) / COUNT(DISTINCT s.ORIGIN_FACILITY_ID) AS AVERAGE_SHIPMENTS
FROM
    shipment s
JOIN
    shipment_status ss ON ss.SHIPMENT_ID = s.SHIPMENT_ID
WHERE
    ss.STATUS_ID = 'SHIPMENT_SHIPPED'
    AND ss.STATUS_DATE BETWEEN '2022-01-01' AND '2022-03-31'
GROUP BY
    MONTHNAME(ss.STATUS_DATE); 
